### ISSUE TITLE
Qiskit and OpenQasm Integration for C3

### ISSUE THREAD

**Issue by lazyoracle** [q-optimize/c3#14]
# Is your feature request related to a problem? Please describe.
There is no seamless way to integrate C3 with high level interfaces such as cirq or qiskit. We would like to change that.

# Describe the solution you'd like
## What
Support for gate level simulation of circuits defined using Qiskit with the C3 tensorflow simulator as a backend

## How
Take circuit transpiled (based on system architecture and gateset provided by C3) by Qiskit compiler into QASM, parse this and create, if required, an intermediary output to be read by the C3 `model_parser` which is then simulated as usual by our C3 simulator

## Why
Qiskit provides a decent high level interface to defining quantum circuits and it's useful to have support for using Qiskit to define circuits which can initially have a gate level simulation (`OpenQasm`) and then a full physics simulation (based on `OpenPulse`)

# Describe alternatives you've considered
None. This is essential.

# Additional context

## TODO:

- [x] Figure out API used by Qiskit to call a backend simulator such as the `QasmSimulator`
- [x] Inherit the qiskit `Provider`, `Backend` and `Job` Classes to write our own simulator which is a wrapper around the C3 tensorflow simulator 
- [x] Implement basic backend framework with `C3Provider`, `C3Backend`, `C3Job` and `C3QiskitError`
- [x] Implement framework in `c3_openqasm_simulator` to accept `Qobj` and return `Result`
- [x] Create C3 physical qubits from OpenQasm `Qobj`
- [x] Convert instructions between `Qobj` and C3, essentially map the gateset
- [x] Map `execute()` in `qiskit` to internal C3 interfacing
- [x] Map shots/memory to experiment/population (measurement and readout)
- [x] Create dictionary of results
- [x] Achieve the following consistent interface:

  ```python
  from c3.qiskit import C3Provider
  from qiskit import execute, QuantumCircuit
  qc = QuantumCircuit(2, 2)
  # add quantum gates
  c3_provider = C3Provider()
  c3_backend = c3_provider.get_backend("c3_qasm_simulator")
  c3_backend.set_device_config("device.hjson")
  c3_job = execute(qc, c3_backend, shots=10)
  result = c3_job.result()
  res_counts = result.get_counts(qc)
  print(res_counts)
  ```

- [x] Update tests
- [x] Update examples
- [x] Update docs
- [x] Update workflows with requirements

## References:
* [Qiskit Backends Intro](https://medium.com/qiskit/qiskit-backends-what-they-are-and-how-to-work-with-them-fb66b3bd0463)
* [Class `QasmSimulator`](https://qiskit.org/documentation/_modules/qiskit/providers/aer/backends/qasm_simulator.html#QasmSimulator)
* [Qiskit Simulators](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html)
* [Qiskit `transpile`](https://qiskit.org/documentation/stubs/qiskit.compiler.transpile.html)
* OpenQasm [paper](https://arxiv.org/pdf/1809.03452.pdf) and 
* [OpenQasm 3 docs](https://github.com/Qiskit/openqasm/releases/tag/3.0) - A parser for this is not yet implemented so this will be tackled in an another issue/PR
* [Blog Post on OpenQasm 3](https://medium.com/qiskit/a-new-openqasm-for-a-new-era-of-dynamic-circuits-87f031cac49)
* [PQSC](https://www.zhinst.com/europe/en/products/pqsc-programmable-quantum-system-controller) which is very close to an implementation of `OpenQasm 3`
* [Tutorial on Legacy Backend](https://github.com/Qiskit/qiskit-tutorials/blob/6b9bfd21f7acd4d19721f6a9c2937424de9dc9ab/qiskit/terra/creating_a_provider.ipynb)
* [Blogpost on Legacy Backend](https://medium.com/qiskit/classical-simulators-for-quantum-computers-4b994dad4fa2)
* [Honeywell Provider](https://github.com/qiskit-community/qiskit-honeywell-provider)
* [QCGPU Provider](https://github.com/qiskit-community/qiskit-qcgpu-provider)
* [AQT Provider](https://github.com/qiskit-community/qiskit-aqt-provider)
* [Providers Interface Docs from WIP PR 5406 in qiskit-terra](https://github.com/shaimach/c3po/files/5712097/Providers.Interface.qiskit.providers.Qiskit.0.17.0.documentation.pdf)
* [Example schemas for different `Qobj` dicts](https://github.com/Qiskit/qiskit-terra/tree/master/qiskit/schemas/examples)
* [Qiskit Quantum Operations](https://qiskit.org/documentation/tutorials/circuits/3_summary_of_quantum_operations.html)

**Comment by lazyoracle** [comment]
Closed in #12
